-- Database: postgresql_part1

DROP TABLE IF EXISTS BASICS.STUDENTS;

CREATE TABLE BASICS.STUDENTS(

	-- SERIAL CREATES AN AUTO-INCREMENT INTEGER
	ID SERIAL PRIMARY KEY,

	-- TEXT REPRESENTS STRING DATA
	-- POSTGRES IS GOING TO REJECT IF THIS NAME VALUE IS NOT PRESENT
	NAME TEXT NOT NULL,

	EMAIL TEXT NOT NULL UNIQUE,

	-- CHECK IS USED FOR RULE/CONDITION CHECKING
	AGE INTEGER CHECK(AGE >= 18),

	-- TIMESTAMPTZ STORES DATE, TIME AND ZONE
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()	
);

DROP TABLE IF EXISTS BASICS.PRODUCTS_BASICS;

CREATE TABLE BASICS.PRODUCTS_BASICS(

	-- SERIAL CREATES AN AUTO-INCREMENT INTEGER
	ID SERIAL PRIMARY KEY,

	NAME VARCHAR(100) NOT NULL,

	-- TEXT REPRESENTS STRING DATA
	DESCRIPTION TEXT,

	STOCK INTEGER DEFAULT 0,

	-- BIGINT REPRESENTS AN INTEGER GREATER THAN INTEGER
	TOTAL_VIEWS BIGINT DEFAULT 0,

	-- NUMERIC REPRESENTS EXACT DECIMAL VALUE
	PRICE NUMERIC(10,2),

	IS_ACTIVE BOOLEAN DEFAULT TRUE,

	-- TIMESTAMPTZ STORES DATE, TIME AND ZONE
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()	
);


DROP TABLE IF EXISTS BASICS.APP_EVENTS;

CREATE TABLE BASICS.APP_EVENTS(

	-- UUID
	ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),

	EVENT_NAME TEXT NOT NULL,

	-- JSONB 
	METADATA JSONB DEFAULT '{}'::JSONB,

	-- TIMESTAMPTZ STORES DATE, TIME AND ZONE
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()	
);

DROP TABLE IF EXISTS BASICS.VALUE_EXAMPLES;

CREATE TABLE BASICS.VALUE_EXAMPLES(

	ID SERIAL PRIMARY KEY,

	NICKNAME TEXT,

	BIO TEXT, 

	SCORE INTEGER,

	-- TIMESTAMPTZ STORES DATE, TIME AND ZONE
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()	
);

